"""add timestamps to companies table

Revision ID: 2a797d0cef2c
Revises: ad0637e64ca1
Create Date: 2023-03-18 12:46:17.108950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a797d0cef2c'
down_revision = 'ad0637e64ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
