"""create competencies table

Revision ID: 029337c9f74f
Revises: 0fdc0dee6e68
Create Date: 2023-03-17 23:01:26.757496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029337c9f74f'
down_revision = '0fdc0dee6e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
