"""create reports table

Revision ID: 970a5762f962
Revises: f9838ab57754
Create Date: 2023-03-18 00:08:02.108909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970a5762f962'
down_revision = 'f9838ab57754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_reports_id'), 'student_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_reports_id'), table_name='student_reports')
    op.drop_table('student_reports')
    # ### end Alembic commands ###
