"""create company_subscriber table

Revision ID: ad0637e64ca1
Revises: 6c50622b1355
Create Date: 2023-03-18 12:45:35.375340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad0637e64ca1'
down_revision = '6c50622b1355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_subscriber',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'student_id')
    )
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'updated_at')
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('companies', sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('company_subscriber')
    # ### end Alembic commands ###
