"""create companies table

Revision ID: 689d364bd4a8
Revises: 
Create Date: 2023-03-17 00:27:18.188448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689d364bd4a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('has_accreditation', sa.Boolean(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('inn', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Enum('small', 'middle', 'large', 'huge', name='companyemployeecount'), nullable=False),
    sa.Column('status', sa.Enum('recent', 'active', 'moderation', 'requestToDelete', 'deleted', 'blocked', name='companystatus'), nullable=False),
    sa.Column('reason_rejection', sa.String(), nullable=True),
    sa.Column('active_project_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    sa.Enum('small', 'middle', 'large', 'huge', name='companyemployeecount').drop(op.get_bind(), checkfirst=False)
    sa.Enum('recent', 'active', 'moderation', 'requestToDelete', 'deleted', 'blocked', name='companystatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
