"""add student_competence table

Revision ID: e5467afa3f18
Revises: 032467136197
Create Date: 2023-03-18 23:46:37.828082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5467afa3f18'
down_revision = '032467136197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_competence',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'competency_id')
    )
    op.add_column('competencies', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('competencies', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('competencies', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('competencies', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key('competencies_creator_id', 'competencies', 'users', ['creator_id'], ['id'])
    op.create_foreign_key('competencies_updater_id', 'competencies', 'users', ['updater_id'], ['id'])
    op.create_unique_constraint('competencies_unique_name', 'competencies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competencies_creator_id', 'competencies', type_='foreignkey')
    op.drop_constraint('competencies_updater_id', 'competencies', type_='foreignkey')
    op.drop_constraint('competencies_unique_name', 'competencies', type_='unique')
    op.drop_column('competencies', 'updater_id')
    op.drop_column('competencies', 'creator_id')
    op.drop_column('competencies', 'updated_at')
    op.drop_column('competencies', 'created_at')
    op.drop_table('student_competence')
    # ### end Alembic commands ###
