"""add project_managers table

Revision ID: 69ac076e27c6
Revises: e5467afa3f18
Create Date: 2023-03-19 00:20:23.306559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ac076e27c6'
down_revision = 'e5467afa3f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_managers',
    sa.Column('participant', sa.Enum('Head', 'Other', name='projectparticipant'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_managers')
    sa.Enum(name='projectparticipant').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
