"""create students table

Revision ID: 694233258743
Revises: 573108f3c881
Create Date: 2023-03-17 23:23:27.153724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694233258743'
down_revision = '573108f3c881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('resume_content_type', sa.String(length=255), nullable=True),
    sa.Column('resume_file_size', sa.Integer(), nullable=True),
    sa.Column('is_full_feedback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
