"""add company field to project model

Revision ID: 201b21b507a5
Revises: 69ac076e27c6
Create Date: 2023-03-19 00:54:55.758634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201b21b507a5'
down_revision = '69ac076e27c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key('projects_company_id', 'projects', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('projects_updater_id', 'projects', 'users', ['updater_id'], ['id'])
    op.create_foreign_key('projects_creator_id', 'projects', 'users', ['creator_id'], ['id'])
    op.add_column('student_reports', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('student_reports', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_reports', 'updated_at')
    op.drop_column('student_reports', 'created_at')
    op.drop_constraint('projects_company_id', 'projects', type_='foreignkey')
    op.drop_constraint('projects_updater_id', 'projects', type_='foreignkey')
    op.drop_constraint('projects_creator_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'updater_id')
    op.drop_column('projects', 'creator_id')
    op.drop_column('projects', 'company_id')
    # ### end Alembic commands ###
