"""create bids table

Revision ID: 0fdc0dee6e68
Revises: 689d364bd4a8
Create Date: 2023-03-17 22:56:03.294953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdc0dee6e68'
down_revision = '689d364bd4a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'viewed', 'revoked', 'expired', 'inTeam', 'refusal', name='bidstatus'), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('refusal_reason', sa.String(), nullable=True),
    sa.Column('is_archival', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    sa.Enum(name='bidstatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
