"""create projects table

Revision ID: 78fff67b91ee
Revises: 25f3aaeb9b48
Create Date: 2023-03-18 01:03:10.403991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fff67b91ee'
down_revision = '25f3aaeb9b48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('projectRoleId', sa.Integer(), nullable=True),
    sa.Column('contingentPersonId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('Software', 'SoftwareAndHardware', 'Research', 'Startup', 'Internship', name='projecttypeenum'), nullable=False),
    sa.Column('view', sa.Enum('DigitalAcademy', 'AdvancedEngineeringSchool', 'GPO', name='projectview'), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Open', 'Completed', 'Done', 'Blocked', name='projectstatusenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('problem', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('what_will_get', sa.String(), nullable=False),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('report', sa.String(), nullable=True),
    sa.Column('reason_rejection', sa.String(), nullable=True),
    sa.Column('application_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('members')
    sa.Enum(name='projectview').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='projecttypeenum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='projectstatusenum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
