"""create reviews table

Revision ID: e4cd1f8f51e2
Revises: 970a5762f962
Create Date: 2023-03-18 00:22:10.387774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cd1f8f51e2'
down_revision = '970a5762f962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_reviews_id'), 'member_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_reviews_id'), table_name='member_reviews')
    op.drop_table('member_reviews')
    # ### end Alembic commands ###
