"""add company_type_activity table

Revision ID: f961c5c030a5
Revises: 3498702aaf9c
Create Date: 2023-03-18 23:09:43.647595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f961c5c030a5'
down_revision = '3498702aaf9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_type_activity',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['type_activity_id'], ['type_activity.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'type_activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_type_activity')
    # ### end Alembic commands ###
