"""create subject_areas table

Revision ID: 6c50622b1355
Revises: 78fff67b91ee
Create Date: 2023-03-18 12:08:46.139989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c50622b1355'
down_revision = '78fff67b91ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_areas_id'), 'subject_areas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_areas_id'), table_name='subject_areas')
    op.drop_table('subject_areas')
    # ### end Alembic commands ###
