"""add student_subject_area table

Revision ID: 032467136197
Revises: f961c5c030a5
Create Date: 2023-03-18 23:27:14.229396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032467136197'
down_revision = 'f961c5c030a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subject_area',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_area_id'], ['subject_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'subject_area_id')
    )
    op.add_column('subject_areas', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('subject_areas', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('subject_areas', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('subject_areas', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('subject_areas_unique_name', 'subject_areas', ['name'])
    op.create_foreign_key('subject_areas_updater_id', 'subject_areas', 'users', ['updater_id'], ['id'])
    op.create_foreign_key('subject_areas_creator_id', 'subject_areas', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_areas_updater_id', 'subject_areas', type_='foreignkey')
    op.drop_constraint('subject_areas_creator_id', 'subject_areas', type_='foreignkey')
    op.drop_constraint('subject_areas_unique_name', 'subject_areas', type_='unique')
    op.drop_column('subject_areas', 'updater_id')
    op.drop_column('subject_areas', 'creator_id')
    op.drop_column('subject_areas', 'updated_at')
    op.drop_column('subject_areas', 'created_at')
    op.drop_table('student_subject_area')
    # ### end Alembic commands ###
