"""add student_id field to student_reports table

Revision ID: f3a2cd19a62c
Revises: 0b35aa085d6c
Create Date: 2023-03-19 22:10:40.499454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a2cd19a62c'
down_revision = '0b35aa085d6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_reports', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_student_reports_student_id'), 'student_reports', ['student_id'], unique=False)
    op.create_foreign_key('student_reports_student_id', 'student_reports', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_reports_student_id', 'student_reports', type_='foreignkey')
    op.drop_index(op.f('ix_student_reports_student_id'), table_name='student_reports')
    op.drop_column('student_reports', 'student_id')
    # ### end Alembic commands ###
