"""sort fields in companies table

Revision ID: dbd152c8310d
Revises: 5cc844cb4f3e
Create Date: 2023-03-18 22:33:02.952554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd152c8310d'
down_revision = '5cc844cb4f3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'has_accreditation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_companies_name', table_name='companies')
    op.create_unique_constraint('companies_inn_unique', 'companies', ['inn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_inn_unique', 'companies', type_='unique')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.alter_column('companies', 'has_accreditation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
