"""add site field to company model

Revision ID: 8700b7c34060
Revises: 7b844925791d
Create Date: 2023-03-27 21:17:10.107640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8700b7c34060'
down_revision = '7b844925791d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('site', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'site')
    # ### end Alembic commands ###
