"""create invitations table

Revision ID: 573108f3c881
Revises: 029337c9f74f
Create Date: 2023-03-17 23:13:35.024524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573108f3c881'
down_revision = '029337c9f74f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'viewed', 'revoked', 'expired', 'consent', 'refusal', 'in_team', 'rejection', name='invitationstatus'), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_archival', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_table('invites')
    sa.Enum(name='invitationstatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
