"""add curators table

Revision ID: b11a819482be
Revises: 201b21b507a5
Create Date: 2023-03-19 14:33:12.173782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11a819482be'
down_revision = '201b21b507a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curators',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'curator_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curators')
    # ### end Alembic commands ###
