"""add competencies

Revision ID: bc7aff840c44
Revises: f5421d07c9c2
Create Date: 2023-03-25 21:11:48.493241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7aff840c44'
down_revision = 'f5421d07c9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    op.create_table('subject_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subject_areas_id'), 'subject_areas', ['id'], unique=False)
    op.create_table('students_competencies',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.create_table('students_subject_areas',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_area_id'], ['subject_areas.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_subject_areas')
    op.drop_table('students_competencies')
    op.drop_index(op.f('ix_subject_areas_id'), table_name='subject_areas')
    op.drop_table('subject_areas')
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
